set(DIRECTXTK_BIN_DIR "${Orangine_SOURCE_DIR}/../thirdparty/DirectXTK/bin" CACHE PATH "")

if (${Orangine_ARCHITECTURE} MATCHES "x86")
        set(MSVC_ARCHITECTURE Win32)
else()
        set(MSVC_ARCHITECTURE x64)
endif()

if(IS_DIRECTORY "${DIRECTXTK_BIN_DIR}/Desktop_2017_Win10/${MSVC_ARCHITECTURE}/${OE_DEPENDENCY_BUILD_TYPE}")
        set(DIRECTXTK_LIB_DIR "${DIRECTXTK_BIN_DIR}/Desktop_2017_Win10" CACHE PATH "")
elseif(IS_DIRECTORY "${DIRECTXTK_BIN_DIR}/Desktop_2019_Win10/${MSVC_ARCHITECTURE}/${OE_DEPENDENCY_BUILD_TYPE}")
        set(DIRECTXTK_LIB_DIR "${DIRECTXTK_BIN_DIR}/Desktop_2019_Win10" CACHE PATH "")
else()
        message(FATAL_ERROR "Could not find valid DirectXTK build directory ${MSVC_ARCHITECTURE}/${OE_DEPENDENCY_BUILD_TYPE}")
endif()

set(DIRECTXTK_LIBRARIES "${DIRECTXTK_LIB_DIR}/${MSVC_ARCHITECTURE}/${OE_DEPENDENCY_BUILD_TYPE}/DirectXTK12.lib" CACHE PATH "")
