from typing import Any

class SampleScene:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def input(self) -> Any: ...
    @property
    def scene_graph(self) -> Any: ...
